#  -----------
# | UI LAYER  |
#  -----------
services:

  # -- CONTROLLERS --
  App.Ui.Http.Product.ProductsGetController:
    class: ../../src/App/Ui/Http/Product/ProductsGetController
    arguments: []

  # -- CLI COMMANDS --