#  -----------
# | UI LAYER  |
#  -----------
services:
  App.Product.JsonRepository:
    class: ../../src/Product/Infrastructure/Persistence/JsonProductRepository
  App.Product.MongoRepository:
    class: ../../src/Product/Infrastructure/Persistence/MongoProductRepository
    arguments: ['@Shared.ConnectionManager']
  # -- SERVICES --
  App.Product.FindAllProductsQueryHandler:
    class: ../../src/Product/Application/FindAllProductsQueryHandler
    arguments: ['@App.Product.MongoRepository']
    tags:
      - { name: 'queryHandler' }
  # -- CONTROLLERS --
  App.Ui.Http.Product.ProductsGetController:
    class: ../../src/App/Ui/Http/Product/ProductsGetController
    arguments: ['@Shared.QueryBus']
  # -- CONTROLLERS --
  App.Ui.Http.Product.ProductPostController:
    class: ../../src/App/Ui/Http/Product/ProductPostController
    arguments: ['@Shared.CommandBus']
